import type { PolicyPack, PolicyRule } from '@kaibase/shared';

/**
 * Returns the default PolicyPack skeleton for a newly created workspace.
 *
 * The caller must supply the workspace-scoped `workspaceId` and, optionally,
 * a stable `id` for the pack itself.  Rules are returned with deterministic
 * IDs so they can be reproduced across seed runs.
 *
 * Evaluation order: rules are sorted by `priority` ascending (first-match-wins).
 * The pack's own `defaultOutcome` is applied when no rule matches.
 */
export function getDefaultPolicyPack(
  workspaceId: string,
  packId: string = 'default',
): PolicyPack {
  const rules: PolicyRule[] = [
    // -------------------------------------------------------------------------
    // Priority 0 — Hard block: source types that must never generate AI output.
    // Currently empty by default; workspace admins populate the blocklist via UI.
    // The rule is kept enabled so that adding values to `value` takes effect
    // immediately without a policy version bump.
    // -------------------------------------------------------------------------
    {
      id: `${packId}:rule:block-source-type`,
      name: 'Block disallowed source types',
      description:
        'Block AI page generation for source types in the workspace blocklist.' +
        ' Add source type strings to the condition value to activate.',
      priority: 0,
      enabled: true,
      conditions: [
        {
          field: 'source_type',
          operator: 'in',
          // Empty list — no source type is blocked until the admin configures it.
          value: [] as string[],
        },
      ],
      outcome: 'BLOCKED',
    },

    // -------------------------------------------------------------------------
    // Priority 10 — Auto-publish pages authored directly by a human user.
    // Users writing their own pages need no AI governance gate.
    // -------------------------------------------------------------------------
    {
      id: `${packId}:rule:auto-publish-user-created`,
      name: 'Auto-publish user-created pages',
      description:
        'Pages created directly by a human user bypass the AI review gate' +
        ' and are published immediately.',
      priority: 10,
      enabled: true,
      conditions: [
        {
          field: 'actor_type',
          operator: 'equals',
          value: 'user',
        },
        {
          field: 'action_type',
          operator: 'equals',
          value: 'page_create',
        },
      ],
      outcome: 'AUTO_PUBLISH',
    },

    // -------------------------------------------------------------------------
    // Priority 20 — Review required: AI is creating a brand-new page.
    // New AI pages carry the most risk; a human must approve before publishing.
    // -------------------------------------------------------------------------
    {
      id: `${packId}:rule:review-ai-page-create`,
      name: 'Require review for AI page creation',
      description:
        'Every new page generated by the AI compiler must be reviewed by' +
        ' a human before it becomes visible in the knowledge space.',
      priority: 20,
      enabled: true,
      conditions: [
        {
          field: 'actor_type',
          operator: 'equals',
          value: 'ai',
        },
        {
          field: 'action_type',
          operator: 'equals',
          value: 'page_create',
        },
      ],
      outcome: 'REVIEW_REQUIRED',
    },

    // -------------------------------------------------------------------------
    // Priority 30 — Draft only: AI is updating an existing page.
    // Updates change existing content; save as draft so the author can diff.
    // -------------------------------------------------------------------------
    {
      id: `${packId}:rule:draft-ai-page-update`,
      name: 'Draft AI page updates',
      description:
        'Proposed updates from the AI compiler are saved as drafts.' +
        ' The page author or a reviewer can inspect the diff and publish.',
      priority: 30,
      enabled: true,
      conditions: [
        {
          field: 'actor_type',
          operator: 'equals',
          value: 'ai',
        },
        {
          field: 'action_type',
          operator: 'equals',
          value: 'page_update',
        },
      ],
      outcome: 'DRAFT_ONLY',
    },

    // -------------------------------------------------------------------------
    // Priority 40 — Auto-publish: lightweight AI ops (classify, summarize).
    // These actions do not touch page content directly; they annotate metadata.
    // -------------------------------------------------------------------------
    {
      id: `${packId}:rule:auto-publish-ai-meta-ops`,
      name: 'Auto-publish AI classification and summarization',
      description:
        'Classification and summarization actions only set metadata fields' +
        ' and do not alter page content, so they can be published automatically.',
      priority: 40,
      enabled: true,
      conditions: [
        {
          field: 'actor_type',
          operator: 'equals',
          value: 'ai',
        },
        {
          field: 'action_type',
          operator: 'in',
          value: ['classify', 'summarize'],
        },
      ],
      outcome: 'AUTO_PUBLISH',
    },
  ];

  return {
    id: packId,
    workspaceId,
    name: 'Default Policy',
    version: 1,
    isActive: true,
    rules,
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: 'system',
  };
}
